### ISSUE TITLE
训练过程中出现AssertionError: freq : tensor([[nan], 

### ISSUE THREAD

**Issue by jiuyuzhang** [Levantespot/UDA_for_RS#3]
作者您好，我在复现代码的过程中遇到如下的情况，请您帮我看一下问题出在哪里
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2023-11-16 17:49:07,703 - mmseg - INFO - Loaded 398 images from /home/test/桌面/UDA_for_RS-main/data/vaihingen/img_dir/val
2023-11-16 17:49:07,703 - mmseg - INFO - Start running, host: test@Precision-3650-Tower, work_dir: /home/test/桌面/UDA_for_RS-main/work_dirs
2023-11-16 17:49:07,703 - mmseg - INFO - workflow: [('train', 1)], max: 4000 iters
2023-11-16 17:49:30,553 - mmseg - INFO - Iter [50/4000]	lr: 3.227e-06, eta: 0:29:58, time: 0.455, data_time: 0.012, memory: 6141, decode.loss_seg: 0.9093, decode.acc_seg: 14.4824, mix.decode.loss_seg: 0.7719, mix.decode.acc_seg: 32.4202
2023-11-16 17:49:52,449 - mmseg - INFO - Iter [100/4000]	lr: 6.437e-06, eta: 0:29:01, time: 0.438, data_time: 0.018, memory: 6141, decode.loss_seg: 0.8860, decode.acc_seg: 31.5676, mix.decode.loss_seg: 0.7031, mix.decode.acc_seg: 48.5760
2023-11-16 17:50:14,683 - mmseg - INFO - Iter [150/4000]	lr: 9.563e-06, eta: 0:28:37, time: 0.445, data_time: 0.014, memory: 6141, decode.loss_seg: 0.8038, decode.acc_seg: 33.1988, mix.decode.loss_seg: 0.6147, mix.decode.acc_seg: 56.0857
2023-11-16 17:50:37,044 - mmseg - INFO - Iter [200/4000]	lr: 1.261e-05, eta: 0:28:15, time: 0.447, data_time: 0.013, memory: 6141, decode.loss_seg: 0.6368, decode.acc_seg: 40.7973, mix.decode.loss_seg: 0.6524, mix.decode.acc_seg: 58.4451
2023-11-16 17:51:00,152 - mmseg - INFO - Iter [250/4000]	lr: 1.557e-05, eta: 0:28:05, time: 0.462, data_time: 0.037, memory: 6141, decode.loss_seg: 0.7020, decode.acc_seg: 46.7869, mix.decode.loss_seg: 0.6864, mix.decode.acc_seg: 56.9241
2023-11-16 17:51:22,146 - mmseg - INFO - Iter [300/4000]	lr: 1.844e-05, eta: 0:27:37, time: 0.440, data_time: 0.014, memory: 6141, decode.loss_seg: 0.5795, decode.acc_seg: 51.9380, mix.decode.loss_seg: 0.4575, mix.decode.acc_seg: 64.6601
2023-11-16 17:51:43,970 - mmseg - INFO - Iter [350/4000]	lr: 2.124e-05, eta: 0:27:08, time: 0.436, data_time: 0.008, memory: 6141, decode.loss_seg: 0.6146, decode.acc_seg: 55.4345, mix.decode.loss_seg: 0.6307, mix.decode.acc_seg: 62.4056
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 398/398, 20.9 task/s, elapsed: 19s, ETA:     0s2023-11-16 17:52:26,727 - mmseg - INFO - per class results:
2023-11-16 17:52:26,728 - mmseg - INFO - 
+--------------------+-------+-------+
|       Class        |  IoU  |  Acc  |
+--------------------+-------+-------+
| impervious_surface | 64.04 | 72.59 |
|      building      | 56.39 |  89.0 |
|   low_vegetation   | 24.41 |  42.8 |
|        tree        |  27.8 | 30.63 |
|        car         | 27.22 | 73.66 |
|      clutter       |  0.71 |  1.05 |
+--------------------+-------+-------+
2023-11-16 17:52:26,728 - mmseg - INFO - Summary:
2023-11-16 17:52:26,728 - mmseg - INFO - 
+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 60.39 | 33.43 | 51.62 |
+-------+-------+-------+
2023-11-16 17:52:26,730 - mmseg - INFO - Iter [398/4000]	lr: 2.395e-05, eta: 0:26:44, time: 0.443, data_time: 0.009, memory: 6141, aAcc: 0.6039, mIoU: 0.3343, mAcc: 0.5162, IoU.impervious_surface: 0.6404, IoU.building: 0.5639, IoU.low_vegetation: 0.2441, IoU.tree: 0.2780, IoU.car: 0.2722, IoU.clutter: 0.0071, Acc.impervious_surface: 0.7259, Acc.building: 0.8900, Acc.low_vegetation: 0.4280, Acc.tree: 0.3063, Acc.car: 0.7366, Acc.clutter: 0.0105, decode.loss_seg: 0.4256, decode.acc_seg: 51.6083, mix.decode.loss_seg: 0.4195, mix.decode.acc_seg: 64.8112
2023-11-16 17:52:49,077 - mmseg - INFO - Iter [450/4000]	lr: 2.657e-05, eta: 0:29:05, time: 0.859, data_time: 0.422, memory: 6141, decode.loss_seg: 0.4959, decode.acc_seg: 54.3103, mix.decode.loss_seg: 0.4729, mix.decode.acc_seg: 64.0733
Traceback (most recent call last):
  File "/home/test/桌面/UDA_for_RS-main/tools/train.py", line 181, in <module>
    main(sys.argv[1:])
  File "/home/test/桌面/UDA_for_RS-main/tools/train.py", line 170, in main
    train_segmentor(
  File "/home/test/桌面/UDA_for_RS-main/mmseg/apis/train.py", line 131, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/test/anaconda3/envs/confeti/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/test/anaconda3/envs/confeti/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/test/anaconda3/envs/confeti/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/test/桌面/UDA_for_RS-main/mmseg/models/uda/dacs.py", line 215, in train_step
    log_vars = self(**data_batch)
  File "/home/test/anaconda3/envs/confeti/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/test/anaconda3/envs/confeti/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/test/桌面/UDA_for_RS-main/mmseg/models/segmentors/base.py", line 109, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/test/桌面/UDA_for_RS-main/mmseg/models/uda/dacs.py", line 257, in forward_train
    weights = self.get_dynamic_class_weight(gt_semantic_seg)
  File "/home/test/桌面/UDA_for_RS-main/mmseg/models/uda/dacs.py", line 134, in get_dynamic_class_weight
    assert not torch.isnan(cur_class_weights).any(), 'freq : {}\ne_1_minus_freq: {}'.format(freq, e_1_minus_freq)
AssertionError: freq : tensor([[nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan]], device='cuda:0')
e_1_minus_freq: tensor([[nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan]], device='cuda:0')

进程已结束，退出代码为 1

**Comment by Levantespot** [comment]
你好，请问你是自己复现时出现的问题，还是使用的仓库文件出现的问题？我这边初步判断是除零导致的问题。如果是自己复现出现的问题，注意在除法运算的分母中加上一个小数（比如1e-6），可以避免类似的问题。

**Comment by jiuyuzhang** [comment]
我是复现时出现的问题，加上小数解决了，可以继续训练，谢谢！
